<?php

declare(strict_types=1);

namespace ComplyOps\Control;


if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Legacy control ID to shared test_key mappings.
 */
final class ControlTestKeyMap {

	/** @var array<string, string> */
	private const MAP = array(
		'GDPR-CONSENT-001' => 'consent.mechanism_present',
		'GDPR-CONSENT-002' => 'consent.nonessential_blocked_pre_consent',
		'GDPR-CONSENT-003' => 'consent.analytics_default_denied',
		'GDPR-CONSENT-004' => 'consent.marketing_default_denied',
		'GDPR-CONSENT-005' => 'consent.withdrawal_available',
		'GDPR-CONSENT-006' => 'consent.preferences_persisted',
		'GDPR-CONSENT-007' => 'consent.version_recorded',
		'GDPR-CONSENT-008' => 'consent.categories_separated',
		'GDPR-TRACKING-001' => 'tracking.ga_blocked_pre_consent',
		'GDPR-TRACKING-002' => 'tracking.gtm_blocked_pre_consent',
		'GDPR-TRACKING-003' => 'tracking.unknown_scripts_review',
		'GDPR-TRACKING-004' => 'tracking.cookie_inventory',
		'GDPR-TRACKING-005' => 'tracking.ad_defaults_denied',
		'GDPR-GA-001'      => 'tracking.ga_consent_mode',
		'GDPR-GA-002'      => 'tracking.ga_analytics_storage_denied',
		'GDPR-GA-003'      => 'tracking.ga_ad_storage_denied',
		'GDPR-GA-004'      => 'tracking.ga_ad_user_data_denied',
		'GDPR-GA-005'      => 'tracking.ga_ad_personalization_denied',
		'GDPR-GA-006'      => 'governance.manual_evidence',
		'GDPR-GA-007'      => 'governance.manual_evidence',
		'GDPR-GA-008'      => 'governance.manual_evidence',
		'GDPR-GA-009'      => 'data.ga_pii_payload',
		'GDPR-GA-010'      => 'tracking.ga_duplicate_implementation',
		'GDPR-EMBED-001'   => 'embed.youtube_gated',
		'GDPR-EMBED-002'   => 'embed.third_party_inventory',
		'GDPR-FORM-001'    => 'data.form_inventory',
		'GDPR-FORM-002'    => 'forms.marketing_consent_review',
		'GDPR-FORM-003'    => 'forms.privacy_notice_at_collection',
		'GDPR-FORM-004'    => 'data.sensitive_fields_identified',
		'GDPR-FORM-005'    => 'forms.retention_review',
		'GDPR-WP-001'      => 'wp.privacy_policy_page',
		'GDPR-WP-002'      => 'wp.export_tools_available',
		'GDPR-WP-003'      => 'wp.erasure_tools_available',
		'GDPR-WP-004'      => 'access.open_registration_review',
		'GDPR-WP-005'      => 'wp.comment_privacy',
		'GDPR-WP-006'      => 'exposure.rest_user_enumeration',
		'GDPR-PII-001'     => 'data.pii_in_analytics_urls',
		'GDPR-PII-002'     => 'data.pii_in_analytics_urls',
		'GDPR-PII-003'     => 'data.pii_in_urls',
		'GDPR-PII-004'     => 'data.pii_in_urls',
		'GDPR-RETENTION-001' => 'governance.manual_evidence',
		'GDPR-RETENTION-002' => 'governance.manual_evidence',
		'GDPR-RETENTION-003' => 'retention.evidence_retention_configured',
		'GDPR-RETENTION-004' => 'retention.jobs_configured',
		'GDPR-SEC-001'     => 'transport.https_enabled',
		'GDPR-SEC-002'     => 'wp.core_version_supported',
		'GDPR-SEC-003'     => 'platform.plugin_posture',
		'GDPR-SEC-004'     => 'access.administrator_inventory',
		'GDPR-CONSENT-009' => 'consent.accept_reject_parity',
		'GDPR-CONSENT-010' => 'consent.withdrawal_stops_processing',
		'GDPR-CONSENT-011' => 'consent.record_completeness',
		'GDPR-WP-007'      => 'wp.export_erasure_available',
		'GDPR-WP-008'      => 'privacy.rights_mechanisms_discoverable',
		'GDPR-GOV-001'     => 'governance.manual_evidence',
		'GDPR-GOV-002'     => 'governance.manual_evidence',
		'GDPR-GOV-003'     => 'governance.manual_evidence',
		'GDPR-GOV-004'     => 'governance.manual_evidence',
		'GDPR-GOV-005'     => 'governance.manual_evidence',
		'GDPR-PII-005'     => 'data.pii_in_urls',
		'OWASP-A01-001'    => 'exposure.rest_user_enumeration',
		'OWASP-A01-002'    => 'access.open_registration_review',
		'OWASP-A01-003'    => 'access.administrator_inventory',
		'OWASP-A02-001'    => 'transport.https_enabled',
		'OWASP-A02-002'    => 'data.pii_in_analytics_urls',
		'OWASP-A03-001'    => 'governance.manual_evidence',
		'OWASP-A03-002'    => 'governance.manual_evidence',
		'OWASP-A04-001'    => 'data.form_inventory',
		'OWASP-A04-002'    => 'governance.manual_evidence',
		'OWASP-A05-001'    => 'exposure.debug_mode_disabled',
		'OWASP-A05-002'    => 'exposure.file_editor_disabled',
		'OWASP-A05-003'    => 'access.default_admin_username',
		'OWASP-A06-001'    => 'wp.core_version_supported',
		'OWASP-A06-002'    => 'platform.plugin_posture',
		'OWASP-A06-003'    => 'governance.threat_model_review',
		'OWASP-A07-001'    => 'access.open_registration_review',
		'OWASP-A07-002'    => 'access.mfa_integration',
		'OWASP-A07-003'    => 'access.stale_admin_accounts',
		'OWASP-A08-001'    => 'platform.checksum_integrity',
		'OWASP-A08-002'    => 'platform.trusted_update_sources',
		'OWASP-A09-001'    => 'governance.manual_evidence',
		'OWASP-A09-002'    => 'logging.activity_log_available',
		'OWASP-A09-003'    => 'logging.monitoring_schedule',
		'OWASP-A10-001'    => 'runtime.php_error_leakage',
		'OWASP-A10-002'    => 'runtime.http_500_pattern',
		'OWASP-A10-003'    => 'runtime.failed_cron_jobs',
		'OWASP-A01-004'    => 'exposure.private_content_leakage',
		'OWASP-A03-003'    => 'platform.checksum_integrity',
		'OWASP-A03-004'    => 'platform.unexpected_executables',
		'OWASP-A06-004'    => 'access.rate_limiting_present',
		'OWASP-A07-004'    => 'access.session_timeout',
		'OWASP-A08-003'    => 'platform.trusted_update_sources',
		'OWASP-EXT-001'    => 'exposure.outbound_request_controls',
		'OWASP-EXT-002'    => 'transport.security_headers',
		'HIPAA-ACCESS-001' => 'access.administrator_inventory',
		'HIPAA-ACCESS-002' => 'governance.manual_evidence',
		'HIPAA-AUDIT-001'  => 'logging.activity_log_available',
		'HIPAA-ENCRYPT-001' => 'transport.https_enabled',
		'HIPAA-ENCRYPT-002' => 'encryption.at_rest_evidence',
		'HIPAA-BAA-001'    => 'governance.manual_evidence',
		'HIPAA-BREACH-001' => 'governance.manual_evidence',
		'HIPAA-TRAIN-001'  => 'governance.manual_evidence',
		'HIPAA-SCOPE-001'  => 'governance.manual_evidence',
		'HIPAA-DATA-001'   => 'data.ephi_inventory',
		'HIPAA-ACCESS-003' => 'access.stale_admin_accounts',
		'HIPAA-ACCESS-004' => 'access.mfa_integration',
		'HIPAA-AUDIT-002'  => 'logging.activity_log_available',
		'HIPAA-AUDIT-003'  => 'governance.manual_evidence',
		'HIPAA-TRANS-001'  => 'transmission.email_ephi_flag',
		'HIPAA-ENCRYPT-003' => 'encryption.at_rest_evidence',
		'HIPAA-INTEG-001'  => 'integrity.unauthorized_alteration',
		'HIPAA-BC-001'     => 'governance.manual_evidence',
		'HIPAA-RISK-001'   => 'governance.manual_evidence',
		'HIPAA-MIN-001'    => 'governance.manual_evidence',
		'HIPAA-PATIENT-001' => 'governance.manual_evidence',
		'HIPAA-TECH-009'   => 'exposure.rest_user_enumeration',
		'HIPAA-TECH-010'   => 'wp.core_version_supported',
		'HIPAA-TECH-011'   => 'platform.plugin_posture',
		'HIPAA-AUDIT-002B' => 'logging.monitoring_schedule',
		'SOC2-C1-003'      => 'data.pii_in_analytics_urls',
		'SOC2-P3-002'      => 'data.form_inventory',
		'SOC2-P3-003'      => 'data.sensitive_fields_identified',
		'SOC2-CC10-001'    => 'governance.manual_evidence',
		'SOC2-CC10-002'    => 'governance.manual_evidence',
		'SOC2-CC4-004'     => 'logging.monitoring_schedule',
		'SOC2-CC4-005'     => 'retention.evidence_retention_configured',
		'SOC2-CC6-003'     => 'access.administrator_inventory',
		'SOC2-CC6-007'     => 'transport.https_enabled',
		'SOC2-CC6-009'     => 'exposure.rest_user_enumeration',
		'SOC2-CC6-010'     => 'access.open_registration_review',
		'SOC2-CC6-011'     => 'data.pii_in_analytics_urls',
		'SOC2-CC7-002'     => 'wp.core_version_supported',
		'SOC2-CC7-006'     => 'logging.activity_log_available',
		'SOC2-CC7-007'     => 'platform.plugin_posture',
		'SOC2-CC9-004'     => 'platform.plugin_posture',
		'SOC2-CC9-005'     => 'data.form_inventory',
		'SOC2-CC6-012'     => 'access.mfa_integration',
		'SOC2-CC7-008'     => 'runtime.failed_cron_jobs',
		'SOC2-A1-005'      => 'retention.jobs_configured',
		'SOC2-CC9-006'     => 'governance.manual_evidence',
		'OWASP-A02-003'    => 'transport.hsts_present',
	);

	public static function for_control_id( string $control_id ): ?string {
		if ( isset( self::MAP[ $control_id ] ) ) {
			return self::MAP[ $control_id ];
		}

		if ( str_starts_with( $control_id, 'SOC2-' ) ) {
			return 'governance.manual_evidence';
		}

		return null;
	}
}
